### ISSUE TITLE
Update code examples in line with spec

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-java-examples#1]

**Comment by jonnyry** [comment]
Create versioned repo in line with other gp connect repos?

**Comment by lucywilcock** [comment]
I have completed the DSTU2 examples in branch update-dstu2. This has been pushed to the release branch 0.5.0.

Each of the interactions for the foundations pack in STU3 has an example in branch update-stu3. The [appointments interactions](https://developer.nhs.uk/apis/gpconnect-1-1-0/appointments.html#spine-interactions) still need doing for V1.1.0 and [structured record](https://developer.nhs.uk/apis/gpconnect-1-2-0/accessrecord_structured.html#spine-interactions) will need to be completed for V1.2.0.

**Comment by lucywilcock** [comment]
Damian is now working on this

**Comment by lucywilcock** [comment]
Done as of 1.2.2
